[package]
name = "barter-integration"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Logging
tracing = "0.1.29"

# Async
tokio = { version = "1.14.0", features = ["full"] }
tokio-stream = { version = "0.1.7", features = ["sync"] }
tokio-tungstenite = { version = "0.15.0", features = ["rustls-tls"] }
futures = "0.3.19"
async-trait = "0.1.52"
pin-project = "1.0.10"

# Error
thiserror = "1.0.30"

# SerDe
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"

# Misc
chrono = {version = "0.4.19", features = ["serde"]}
rust_decimal = "1.22.0"