[package]
name = "barter-integration"
version = "0.3.4"
authors = ["keirbailey <keirinvestment@gmail.com>"]
edition = "2021"
license = "MIT"
documentation = "https://docs.rs/barter-integration/"
repository = "https://gitlab.com/open-source-keir/financial-modelling/trading/barter-integration-rs"
readme = "README.md"
description = "Low-level framework for composing flexible web integrations, especially with financial exchanges"
keywords = ["trading", "backtesting", "crypto", "stocks", "investment"]
categories = ["accessibility", "simulation"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Logging
tracing = "0.1.29"

# Async
tokio = { version = "1.20.1", features = ["net", "sync", "macros", "rt-multi-thread"] }
tokio-tungstenite = { version = "0.17.2", features = ["rustls-tls-webpki-roots"] }
futures = "0.3.21"
async-trait = "0.1.57"
pin-project = "1.0.11"

# Error
thiserror = "1.0.32"

# SerDe
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.83"

# Misc
chrono = "0.4.21"
